Dropped unused Python module zappix-api from jm1.packages.ansible role
On newer Debian based distributions such as Debian 13 (Trixie), trying
to install Python modules with pip to the system environment fails
because Debian's system environment is marked as externally managed:

  error: externally-managed-environment

  × This environment is externally managed
  ╰─> To install Python packages system-wide, try apt install
      python3-xyz, where xyz is the package you are trying to
      install.

      If you wish to install a non-Debian-packaged Python package,
      create a virtual environment using python3 -m venv path/to/venv.
      Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
      sure you have python3-full installed.

      If you wish to install a non-Debian packaged Python application,
      it may be easiest to use pipx install xyz, which will manage a
      virtual environment for you. Make sure you have pipx installed.

      See /usr/share/doc/python3.11/README.venv for more information.

  note: If you believe this is a mistake, please contact your Python
        installation or OS distribution provider. You can override
        this, at the risk of breaking your Python installation or OS,
        by passing --break-system-packages.
  hint: See PEP 668 for the detailed specification.

Ansible's zabbix_* modules are not used by any jm1.* collection or
role. To avoid interference with system-wide Python packages, the
Python module zappix-api is dropped.